### ISSUE TITLE
RkLog.h: No such file or directory

### ISSUE THREAD

**Issue by magnetophon** [geontime/geonkick#26]
When I try to build 1.9.2 on NixOS, I get:

```
/tmp/nix-build-geonkick-1.9.2.drv-0/source/src/globals.h:45:10: fatal error: RkLog.h: No such file or directory
```

Edit:

Ah, the Arch pkg gave me the winning hint:
I needed to set ``cmakeFlags = [ "-DGKICK_REDKITE_SDK_PATH=${redkite}" ];``
It's running now.

How is geonkick normaly supposed to find redkite?

**Comment by iurienistor** [comment]
@magnetophon
You need to install Redkite. But since you are doing packaging you'll need to also to specify the Redkite install path.

For Geonkick:
When building Geonkick the build will look for installed Redkite (say GKICK_REDKITE_SDK_PATH = /mydir):
for headers at : ${GKICK_REDKITE_SDK_PATH}/include/redkite
for static library at: ${GKICK_REDKITE_SDK_PATH}/lib

For Redkite:
When building Redkite you'll need also to specify
CMAKE_INSTALL_LIBDIR = /mydir/
CMAKE_INSTALL_PREFIX = /mydir/
that is be the same as GKICK_REDKITE_SDK_PATH = /mydir

**Comment by iurienistor** [comment]
Probably I'll need to add this into README documentation. Think you. :)

**Comment by magnetophon** [comment]
Think *you*!   ;)
