### ISSUE TITLE
Copy/Paste patches between channels?

### ISSUE THREAD

**Issue by unfa** [geontime/geonkick#41]
I wonder if it's possible to duplicate channels and/or copy+paste patches between them.
(I haven't tested the multitimbral plug-in yet)

**Comment by iurienistor** [comment]
yes, in the kit UI there is in button the permits to copy the percussion

**Comment by iurienistor** [comment]
from the kit list also you can change the percussion audio output channel by clicking on #x label

**Comment by iurienistor** [comment]
here is a documentation how to work with kit UI (Kit paragraph) - https://github.com/geontime/geonkick/wiki/Geonkick-Documentation

**Comment by iurienistor** [comment]
Only know I've understood what actually do you mean because working with percussions now the current implemented feature is limited. I'll introduce a copy paste shortcuts between percussions, and also buttons in the top bar menu.

For percussions:
Ctrl+C - copy current percussion
Ctrl+V - paste the copied percussion the current selected percussion
The feature will be available in 2.0 release.

For layers:
Will be developed after release 2.0

**Comment by iurienistor** [comment]
Implemented for percussion. Now it is master and will be available in v 2.0 that is going to be released soon. The feature will be documented too.
