### ISSUE TITLE
k doesn't produce sound.

### ISSUE THREAD

**Issue by magnetophon** [geontime/geonkick#42]
First of all, great work on 1.10.0, love the new features!

When I hit k, I don't get sound.
When I click the play button, I do.

**Comment by iurienistor** [comment]
Hi, thank you :) ... yes, this I need to fix in Redkite toolkit or I should use different API for X server

**Comment by iurienistor** [comment]
Ok, I've implemented a solution in Redkite to get rid of Xlib API XKeyGrab in Geonkick that wasn't working properly. Now the problem should be fixed. Be sure to have window focus. On hosts, like Ardour, you'll need to enable keyboard input (there is a button). Ctrl+o or Ctrl+s may not work on hosts since is the same Arodur/host is using. Key 'k' should work.

The fix now is in master, and will be available in the release 2.0. To compile the fix from master you need first to update Redkite from master (build and install). Thank you!

**Comment by magnetophon** [comment]
Thank *you*! That was quick!
