### ISSUE TITLE
Feature request: velocity modulation of all parameters

### ISSUE THREAD

**Issue by magnetophon** [geontime/geonkick#48]
I love the sounds and the workflow of the latest Geonkick, chapeau!

The biggest downside to me is the static nature of the sounds.
The consistency is great to have though! 

Would it be possible to render a sample for each velocity separately?
Then you could make an interface like the modulation of helm, but just for the velocity, since that is static per note.

So the workflow would be:
- Click the  "Velocity modulation button"
- the knobs and faders that can modulate turn a different color.
- turn one of those knobs and a pie-slice appears on it, with one end denoting the value at 0 velocity and the other the value at 127 velocity.
- Click the  "Velocity modulation button" again, and the knobs turn back to normal color, but keep any pie-slices.

You could use the same UI paradigm to make a "Stereo offset" button: so render two samples per velocity, one left, one right.

Use case examples would be:
- make the kick brighter and more distorted when louder
- make the snare longer and less noisy when louder
- make the snare and HH use different noise seeds for left and right.

Thanks for considering!

**Comment by iurienistor** [comment]
Currently Geonkick permits only expression for total amplitude of the resulted percussion. Expression for other parameters is not possible for now, there is need for radical change of synthesis workflow, here I explained in more details why -https://gitlab.com/geontime/geonkick/-/issues/132#note_174639853

**Comment by magnetophon** [comment]
Sorry, I missed that feature request. Didn't check on GitLab.

I understand that Geonkick doesn't do synthesis in the audio thread, and I think it's a great feature that you should keep; consistent hits and low on CPU.

You could implement velocity modulation by rendering each sample 127 times, one for each velocity.
That would significantly increase the memory-usage, but not nearly to a problematic amount for modern computers, since most samples are short.
Of course that strategy only works for one modulation parameter, otherwise the number of samples quickly goes out of hand.

**Comment by iurienistor** [comment]
Geonkick use preallocated fixed maximum size buffers that can hold maximum of 4s of 48000 samples, this is done to avoid memory allocations when changing the percussion length. The buffer length is changed only by changing its maximum index.

Thus, for one (mono) percussion the memory is about 0.75 MB, for 127 velocities this this would be around 95MB. This multiplied by 16 percussions would be more than a 1.5G per plugin instance.

If I suppose the user changes a knob  the worker will takes 10ms to generate one sample, than 127 percussion will take ~ 1.3s. This will be totally inconsistent with what the user will hear and see and what it expects by changing, for example,  the cutoff knob from 100Hz to 200Hz, or changing the envelope points. It it will no more be a real time visualization and audio synthesis.

Of course, there can be a button that asks Geonkick to generate all this stuff ones, and next use it as just a sampler that will have the expression for the selected parameters that were modulated by velocity during synthesis. But the next time the user will want to change a parameter will need to wait another 1-2 seconds to generate everything or turn back the mode, make the changes, and than ask Geonkick to generate, and changes its mode of operation.

This can be labeled as  "velocity modulation mode" for Geonkick that works differently, and the user should know what is doing... i.e.  how memory it takes, how it behaves. How to use it in this mode of operation., for example, 5 instances will take already 7 G.

"Of course that strategy only works for one modulation parameter, otherwise the number of samples quickly goes out of hand."

During the generation of samples you can select a list of parameters to depend on velocity, thus there is a need only for 127 samples per percussion no matter how many parameters are modulated.

I don't know If I will think seriously if to develop expression, to develop in the worker thread like this.

**Comment by magnetophon** [comment]
I think the memory could be managed if you allocate only for the percussions that are in use, so a pach with kick/snare/HH would take 285 Mb. 
I must say I underestimated the time it takes to render the samples. That would be kind of a showstopper.

> only for 127 samples per percussion no matter how many parameters are modulated.

Sorry, I wasn't clear: I meant if wou wanted to also map for example notes to synth parameters, in addition to velocity, as requested in the gitlab issue.
Far that, you'd need 127*127 samples.

**Comment by iurienistor** [comment]
I doubt I'll implement this for Geonkick. I'll close this issue. In the future maybe I'll return to it.

**Comment by magnetophon** [comment]
OK, thanks for considering.
